### ISSUE TITLE
Difference from go-avahi-cname

### ISSUE THREAD

**Issue by grishy** [graugans/traefik-avahi-helper#1]
Hi!
I'm really glad you mentioned me 😄

I [thought about doing](https://github.com/grishy/go-avahi-cname/issues/5) the same functionality for Trafik (I use it too) inside go-avahi-cname, but realized that it's not necessary since `*.<anyname>.local` ("all subdomain") is supported. 

You don't have to announce all the entries once every 600 seconds (unlike the subdomain option), which isn't very pretty to be honest. Because it clogs traffic and if a new device appears on the network, it can get an update only after 600 seconds in the worst case.

Can you describe your case, what you needed to use it for. I'm interested + maybe I can help :)

**Comment by graugans** [comment]
I was playing around with Traefik, when I came to a point where I asked my self how to register DNS names in my "Homelab" there is not much I can do in my broadband router, an alternative would be to use an official DNS server and provide it with internal IPS. So I could achieve something like `intranet.mydomain.tld` but this may confuses family members not familiar with concepts like this and they will complain why the service is not available outside the house. It also requires a manual process.

So I came across this article from [Andrew Dupont](https://andrewdupont.net/2022/01/27/using-mdns-aliases-within-your-home-network/), I thought this maybe possible with the approach traefik does by scanning the the Docker Labels. So I searched in this direction and came across [https://www.hardill.me.uk](https://www.hardill.me.uk/wordpress/2020/10/05/traefik-avahi-helper/) which already is what I was looking for. But it uses `nodejs` since I am starting to learn Go I thought this is a nice project to develop in Go. I was searching for Avahi and go + CNAME what brought me to your project. Which mostly fulfills my needs except the fact I was looking for the `abritray-name.local` instead of the subdomain approach you are doing. But yeah it is also a smart way to just announce the service which is asked for. 

My use case with the names like `traefik.local` and `homeserver.local` is to be a independent of the machine the service is running at. But you are right it is also achievable with your `subdomain` service like this starting the subdomain service with `go-avahi-cname subdomain --fqdn homeserver.local` and the register the services subsequently `traefik.homeserver.local` or `grafana.homeserver.local`  But this may can cause issues when splitting services across machines which honestly I should take care of when needed  😄 (YAGNI)

In the end it is some fun project where I already have learned a lot of stuff, I took away a lot from your project and I could use almost 100% of your GitHub Workflows without adapting a lot :-) like the usage of `FROM scratch` as a bare minimum image.

**Comment by grishy** [comment]
Oh, got it.
I gave up on the use of `.local`, and just switched to using a public domain, which reply with a private IP.  
https://who.is/dns/lab.grishy.dev  

Different OS have a different mDNS support. I spent a few days and even [patched wireguard](https://www.reddit.com/r/WireGuard/comments/14v1xt3/wireguard_server_with_mdns_support_avahi/), but gave up at the user device stage.  And mDNS like an additional now for domain.
Have fun 😄

**Comment by graugans** [comment]
Yeah, the VPN fact is another downer I do agree. This is due to the fact `.local` is not available due to the TTL set to -1 or something like this which prevents the multicast messages being transferred across network. I guess in the end I will end up with a similar approach you choose. 😄

**Comment by grishy** [comment]
Write if you have any questions or ideas, I'd be happy to help.
Nice to communicate with you 😄 

p.s.
The problem is how mDNS is handled, usually VPNs just don't work with mDNS (multicast protocols in general) and that on iOS the settings don't change for mDNS.  
The system has like `if (DNS_req.end_with(".local")) -> do specific logic`.
